Vagrant.configure("2") do |config|
  config.vm.box = "docker-ubuntu18"
  config.vm.network "private_network", ip: "172.20.1.11" 
  config.vm.hostname = "k8s-master"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
